from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEVELOPMENT_DIR = ROOT / "docs" / "development"


def main() -> None:
    """Write current entity inventory reports."""
    from scripts.entity_inventory import build_inventory_report

    report = build_inventory_report()
    report["git_head"] = _git_head()
    report["integration_version"] = _integration_version()
    DEVELOPMENT_DIR.mkdir(parents=True, exist_ok=True)
    (DEVELOPMENT_DIR / "entity-inventory-before.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (DEVELOPMENT_DIR / "entity-inventory-before.md").write_text(
        _inventory_markdown(report),
        encoding="utf-8",
    )
    (DEVELOPMENT_DIR / "entity-model-current-state.md").write_text(
        _current_state_markdown(report),
        encoding="utf-8",
    )


def _inventory_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Entity Inventory Before Compact Model",
        "",
        "This report is generated by `python scripts/report_entity_inventory.py`.",
        "Counts are per-circuit entity rows and exclude integration-wide setup "
        "health, dashboard layout, entity detail, and global action controls.",
        "",
        "## Scenario Counts",
        "",
    ]
    for scenario in report["scenarios"]:
        lines.append(f"### {scenario['scenario_id']}")
        lines.append("")
        for variant, variant_report in scenario["variants"].items():
            lines.append(f"#### {variant}")
            lines.append("")
            lines.append(
                "| Detail level | Created | Enabled | Disabled | Hidden | Available |"
            )
            lines.append("|---|---:|---:|---:|---:|---:|")
            for detail_level, detail_report in variant_report[
                "detail_levels"
            ].items():
                lines.append(
                    f"| {detail_level} | "
                    f"{detail_report['created']['total']} | "
                    f"{detail_report['enabled']['total']} | "
                    f"{detail_report['disabled']['total']} | "
                    f"{detail_report['hidden']['total']} | "
                    f"{detail_report['available']['total']} |"
                )
            lines.append("")
    lines.append("## Current Entity Descriptions")
    lines.append("")
    lines.extend(_description_table(report["entity_descriptions"]))
    return "\n".join(lines) + "\n"


def _current_state_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Entity Model Current State",
        "",
        "This document records the pre-compact entity model for PR 1 of the "
        "compact entity migration.",
        "",
        "## Baseline",
        "",
        f"- Current implementation version: {report['integration_version']}.",
        "- Review baseline in the plan: `f0dee7a`.",
        f"- Worktree HEAD for this report: `{report['git_head']}`.",
        "- Current entity detail levels change registry enabled/hidden state; they "
        "do not change which per-circuit entities are constructed.",
        "",
        "## Current Architecture",
        "",
        "- Per-circuit entities use unique IDs shaped as "
        "`{entry_id}_{circuit_id}_{key}`.",
        "- `sensor.py` is the largest surface, with summary, feature, and "
        "diagnostic tiers plus applicability gates by source role, circuit mode, "
        "profile, and stored/configured settings.",
        "- `binary_sensor.py` has diagnostics for learning/data quality/"
        "maintenance, the summary `running` entity, and the feature "
        "`water_flow_mismatch` entity.",
        "- `button.py`, `select.py`, and `number.py` expose controls but do not "
        "currently participate in tier-based creation. Buttons use daily-control "
        "applicability; `alert_sensitivity` is currently kept for every circuit, "
        "including mains.",
        "- `SetupHealthSensor`, demo source sensors, and integration-wide global "
        "buttons/selects are outside per-appliance count targets.",
        "",
        "## Replacement Coverage Notes",
        "",
        "- Health Summary already carries bounded readiness, learning progress, "
        "data-quality problem, maintenance state, active alert count, and next "
        "step fields.",
        "- Activity Summary already carries run-cycle status, count, runtime, duty "
        "cycle, standby status, and operating state fields.",
        "- Electrical Health already carries metric consistency, leg imbalance, "
        "power-quality score/evidence, explanations, and first-check guidance.",
        "- Energy Summary already carries energy, billing, and cost rollups, but "
        "later phases must add or preserve coverage for billing budget usage and "
        "current cost rate before removing those standalone entities.",
        "- Sensitivity, last event, recent activity count, outdoor temperature, "
        "standby threshold, always-on values, and drift metrics should not be "
        "removed in later phases until the replacement surface is complete.",
        "",
        "## Dashboard Dependency Notes",
        "",
        "- The generated dashboard resolves entities by `(domain, entity_key)` and "
        "uses registry entity IDs when available, preserving user-renamed IDs.",
        "- Current dashboard references include `activity_summary`, "
        "`electrical_health`, `energy_summary`, `daily_energy_usage`, mains "
        "balance keys, NILM keys, `outdoor_temperature`, `weather_context`, "
        "`run_cycle_runtime`, `run_cycle_duty_cycle`, `water_flow_correlation`, "
        "solar-flow keys, and utility comparison keys.",
        "- Later compact phases must update the generated dashboard before removed "
        "keys disappear from the entity registry.",
        "",
        "## Entity Description Inventory",
        "",
    ]
    lines.extend(_description_table(report["entity_descriptions"]))
    lines.extend(
        [
            "",
            "## Global Entities Outside Per-Circuit Counts",
            "",
            "| Domain | Key | Unique ID pattern | Notes |",
            "|---|---|---|---|",
        ]
    )
    for row in report["global_entities"]:
        lines.append(
            f"| {row['domain']} | `{row['key']}` | "
            f"`{row['unique_id_pattern']}` | {row['notes']} |"
        )
    lines.extend(
        [
            "",
            "## Representative Count Baseline",
            "",
            "| Scenario | Simple created | Standard created | Expert created | "
            "Simple enabled | Standard enabled | Expert enabled |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for scenario in report["scenarios"]:
        detail_levels = scenario["detail_levels"]
        lines.append(
            f"| {scenario['scenario_id']} | "
            f"{detail_levels['simple']['created']['total']} | "
            f"{detail_levels['standard']['created']['total']} | "
            f"{detail_levels['expert']['created']['total']} | "
            f"{detail_levels['simple']['enabled']['total']} | "
            f"{detail_levels['standard']['enabled']['total']} | "
            f"{detail_levels['expert']['enabled']['total']} |"
        )
    return "\n".join(lines) + "\n"


def _description_table(rows: list[dict[str, Any]]) -> list[str]:
    lines = [
        "| Domain | Key | Tier | Category | Applies | Enabled default | "
        "Visible default | Update frequency | Graphable | Tests | Replacement |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        replacement = row["duplicated_by_or_replaced_with"] or ""
        category = row["category"] or ""
        tier = row["tier"] or "control"
        graphable = "yes" if row["graphable"] else "no"
        enabled = "yes" if row["enabled_default"] else "no"
        visible = "yes" if row["visible_default"] else "no"
        lines.append(
            f"| {row['domain']} | `{row['key']}` | {tier} | {category} | "
            f"{row['applicability']} | {enabled} | {visible} | "
            f"{row['expected_update_frequency']} | {graphable} | "
            f"{row['current_tests']} | {replacement} |"
        )
    return lines


def _git_head() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _integration_version() -> str:
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else "unknown"


if __name__ == "__main__":
    main()
